global:
  checkNewVersion: false
  sendAnonymousUsage: false

entryPoints:
  web:
    address: ":8080"
  health:
    address: ":8082"

providers:
  file:
    directory: /etc/traefik/dynamic
    watch: true

ping:
  entryPoint: health

log:
  format: json
  level: INFO

accessLog:
  format: json
  fields:
    headers:
      defaultMode: drop
